version: '3'

services:
  firefox:
    image: selenium/standalone-firefox:4.6.0-20221104
    container_name: rss-selenium-firefox
    restart: unless-stopped
    shm_size: 1gb
    expose:
      - 4444

  python-rss:
    image: rssgen
    container_name: rss-python
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/rssgen/uploads
      - ./rss:/rssgen/rss

